---
name: Qwiet pre-zero Demo

on:
  push:

jobs:
  Qwiet-Static-Analysis:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Download ShiftLeft CLI
      run: |
        curl https://cdn.shiftleft.io/download/sl > ./sl && chmod a+rx ./sl 

    - name: Run sl analyze
      shell: bash
      run: |
        ./sl analyze --verbose --app newapp --javasrc .
      env:
        SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}

    # - name: Export Sarif Report
    #   shell: bash
    #   run: |
    #     git clone https://github.com/ShiftLeftSecurity/field-integrations report
    #     python3 report/shiftleft-utils/export.py --app multisecrets --format "sarif" --report_file report/qwiet-sarif-report.sarif

    - name: Export Json Report
      shell: bash
      run: |
        git clone https://github.com/ShiftLeftSecurity/field-integrations report
        pip3 install -r report/shiftleft-utils/requirements.txt
        python3 report/shiftleft-utils/export.py --app terraformtest1 --format "json" --report_file report/qwiet-json-report.json  
      env:
        SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}  

    - name: Create Json Report
      shell: bash
      run: |
        url="https://app.shiftleft.io/api/v4/orgs/eba14690-d605-4f85-b5e3-b2992e9174b0/apps/terraformtest1/scans/compare?source=scan.3&target=scan.2"
        curl -s -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${SHIFTLEFT_ACCESS_TOKEN}" "${url}" -o output.json
        cat output.json
        echo "+++++++++++++++++++++++++++++++++++++++++++++++++"
        cat report/qwiet-json-report.json
      env:
        SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}        

    # - name: Upload result to GitHub Code Scanning
    #   uses: github/codeql-action/upload-sarif@v2
    #   with:
    #     sarif_file: report/qwiet-sarif-report.sarif       
